import type {
  Product,
  ProductCategory,
} from "@/features/products/types";

export const productCategories: ProductCategory[] = [
  "Laptop",
  "Smartphone",
  "Desktop",
  "Accessories",
];

export const allProducts: Product[] = [
  {
    id: "iphone-17-pro-max",
    name: "iPhone 17 Pro Max",
    slug: "iphone-17-pro-max",
    category: "Smartphone",
    price: 25499000,
    image: "/images/products/iphone-17-pro-max.png",
    condition: "Brand New",
    stock: 12,
    rating: 4.9,
    sold: 98,
    isFeatured: true,
    isPromo: true,
    createdAt: "2026-07-10",
  },
  {
    id: "macbook-pro-m4",
    name: "MacBook Pro 14″ M4",
    slug: "macbook-pro-m4",
    category: "Laptop",
    price: 25999000,
    image: "/images/products/macbook-pro-m4.png",
    condition: "Brand New",
    stock: 9,
    rating: 4.9,
    sold: 67,
    isFeatured: true,
    isPromo: false,
    createdAt: "2026-07-08",
  },
  {
    id: "mac-mini-m4",
    name: "Mac mini M4 16/512 GB",
    slug: "mac-mini-m4",
    category: "Desktop",
    price: 10499000,
    image: "/images/products/mac-mini-m4.png",
    condition: "Brand New",
    stock: 15,
    rating: 4.8,
    sold: 74,
    isFeatured: true,
    isPromo: true,
    createdAt: "2026-07-06",
  },
  {
    id: "iphone-14-pro",
    name: "iPhone 14 Pro",
    slug: "iphone-14-pro",
    category: "Smartphone",
    price: 9499000,
    image: "/images/products/iphone-14-pro.png",
    condition: "Second",
    stock: 5,
    rating: 4.7,
    sold: 124,
    isFeatured: true,
    isPromo: true,
    createdAt: "2026-07-03",
  },
  {
    id: "macbook-air-m4",
    name: "MacBook Air M4",
    slug: "macbook-air-m4",
    category: "Laptop",
    price: 18999000,
    image: "/images/products/macbook-air-m4.png",
    condition: "Brand New",
    stock: 11,
    rating: 4.8,
    sold: 45,
    isFeatured: false,
    isPromo: false,
    createdAt: "2026-07-01",
  },
  {
    id: "iphone-16",
    name: "iPhone 16",
    slug: "iphone-16",
    category: "Smartphone",
    price: 15999000,
    image: "/images/products/iphone-16.png",
    condition: "Brand New",
    stock: 18,
    rating: 4.8,
    sold: 87,
    isFeatured: false,
    isPromo: true,
    createdAt: "2026-06-28",
  },
  {
    id: "airpods-pro-2",
    name: "AirPods Pro 2",
    slug: "airpods-pro-2",
    category: "Accessories",
    price: 3499000,
    image: "/images/products/airpods-pro-2.png",
    condition: "Brand New",
    stock: 20,
    rating: 4.9,
    sold: 156,
    isFeatured: false,
    isPromo: true,
    createdAt: "2026-06-25",
  },
  {
    id: "mac-studio-m4-max",
    name: "Mac Studio M4 Max",
    slug: "mac-studio-m4-max",
    category: "Desktop",
    price: 38999000,
    image: "/images/products/mac-studio-m4-max.png",
    condition: "Brand New",
    stock: 4,
    rating: 4.9,
    sold: 21,
    isFeatured: false,
    isPromo: false,
    createdAt: "2026-06-20",
  },
  {
    id: "macbook-air-m2",
    name: "MacBook Air M2",
    slug: "macbook-air-m2",
    category: "Laptop",
    price: 13999000,
    image: "/images/products/macbook-air-m2.png",
    condition: "Brand New",
    stock: 14,
    rating: 4.7,
    sold: 89,
    isFeatured: false,
    isPromo: true,
    createdAt: "2026-06-15",
  },
  {
    id: "iphone-15-pro",
    name: "iPhone 15 Pro",
    slug: "iphone-15-pro",
    category: "Smartphone",
    price: 13499000,
    image: "/images/products/iphone-15-pro.png",
    condition: "Second",
    stock: 7,
    rating: 4.8,
    sold: 112,
    isFeatured: false,
    isPromo: false,
    createdAt: "2026-06-10",
  },
  {
    id: "macbook-pro-m2",
    name: "MacBook Pro M2",
    slug: "macbook-pro-m2",
    category: "Laptop",
    price: 14999000,
    image: "/images/products/macbook-pro-m2.png",
    condition: "Second",
    stock: 6,
    rating: 4.6,
    sold: 64,
    isFeatured: false,
    isPromo: true,
    createdAt: "2026-06-05",
  },
  {
    id: "airpods-max",
    name: "AirPods Max",
    slug: "airpods-max",
    category: "Accessories",
    price: 8299000,
    image: "/images/products/airpods-max.png",
    condition: "Brand New",
    stock: 8,
    rating: 4.7,
    sold: 43,
    isFeatured: false,
    isPromo: false,
    createdAt: "2026-05-28",
  },
  {
    id: "iphone-13",
    name: "iPhone 13",
    slug: "iphone-13",
    category: "Smartphone",
    price: 7499000,
    image: "/images/products/iphone-13.png",
    condition: "Second",
    stock: 10,
    rating: 4.6,
    sold: 143,
    isFeatured: false,
    isPromo: true,
    createdAt: "2026-05-20",
  },
  {
    id: "magic-keyboard",
    name: "Apple Magic Keyboard",
    slug: "magic-keyboard",
    category: "Accessories",
    price: 2199000,
    image: "/images/products/magic-keyboard.png",
    condition: "Brand New",
    stock: 23,
    rating: 4.7,
    sold: 91,
    isFeatured: false,
    isPromo: false,
    createdAt: "2026-05-15",
  },
  {
    id: "mac-mini-m2",
    name: "Mac mini M2 8/256 GB",
    slug: "mac-mini-m2",
    category: "Desktop",
    price: 7499000,
    image: "/images/products/mac-mini-m2.png",
    condition: "Second",
    stock: 5,
    rating: 4.6,
    sold: 58,
    isFeatured: false,
    isPromo: true,
    createdAt: "2026-05-08",
  },
  {
    id: "apple-watch-series-10",
    name: "Apple Watch Series 10",
    slug: "apple-watch-series-10",
    category: "Accessories",
    price: 6499000,
    image: "/images/products/apple-watch-series-10.png",
    condition: "Brand New",
    stock: 17,
    rating: 4.8,
    sold: 76,
    isFeatured: false,
    isPromo: false,
    createdAt: "2026-05-01",
  },
];

export const featuredProducts = allProducts
  .filter((product) => product.isFeatured)
  .slice(0, 4);

export const newArrivalProducts = [...allProducts]
  .sort(
    (firstProduct, secondProduct) =>
      new Date(secondProduct.createdAt).getTime() -
      new Date(firstProduct.createdAt).getTime(),
  )
  .slice(0, 4);